### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [szymongrotha/trello_js#1]
- [x] złe wcięcia w kodzie tym razem Ci nie daruję :D !
- [x] jeśli chcesz dodać kanbana do CV to popracuj nad stylami

cała reszta jest w porzadku. 

Pytania dodatkowe do zadania:
- [x] czy wiesz po co stosujemy `var self = this`
- [x] dlaczego przed niektórymi zmiennymi stawiamy znak `$`
- [x] czy rozumiesz ideę jquery jako wrappera dla elementu DOM?

**Comment by szymongrotha** [comment]
1. Wcięcia poprawione ;) (Mam nadzieję 3 razy sprawdzałem:P)
2. Style poprawione

Pytania.
1. Moim zdaniem stosujemy to aby funkcja wewnątrz funkcji kontrującej np. function createColumn() nie gubiła kontekstu czyli - jakbyśmy dali tam "this" zamiast "self" to this wskazywało by na Windows w DOM. Jeżeli funkcja jest zagnieżdżona w funkcji to ma już swoje własne "this" które nie jest zadeklarowane dlatego wskazuje na pusty obiekt - tak to rozumiem swoimi słowami :)

2. Bo korzystają z Jquery żeby łatwiej nam było ja zidentyfikować? 

3. Myślę że tak tworzymy np `$("<header>").css('color', '#FFFFFF');` - która zmieni kolor textu w <header> na biały - ale to nie działa bezpośrednio na drzewie DOM - jest to jedynie odniesienie do niego. (Ale namotałem :P )
